name: 'AI Pull Request Analyst Bot'

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  analyze_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # 更新：安裝 requests 和 google-generativeai
      - name: Install dependencies
        run: pip install requests google-generativeai

      # 更新：傳入 GEMINI_API_KEY 和模型名稱
      - name: Run AI analysis script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # 從 Secrets 讀取金鑰
          GEMINI_MODEL: 'gemini-2.5-flash-lite-preview-06-17' # 使用一個通用的高效模型
        run: python .github/scripts/generate_summary.py
